project:
  type: website
  output-dir: docs

website:
  title: "Zohaib Khan"
  navbar:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/zohaib-khan-5a76611a6/
      - icon: github
        href: https://github.com/zohaib-khan5040
    left:
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: blog/index.qmd
format:
  html:
    theme: cosmo
    css: styles.css



