project:
  type: website
  output-dir: docs

website:
  title: "Zohaib Khan"
  favicon: files/favicon.png
  navbar:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/zohaib-khan-5a76611a6/
      - icon: github
        href: https://github.com/zohaib-khan5040
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=Z-mb0_0AAAAJ&hl=en
    left:
      - text: "Blog"
        href: blog/index.qmd
      - text: "CV"
        href: files/Resume.pdf
format:
  html:
    theme: cosmo
    css: styles.css



